version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing Terraform...
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_windows_amd64.zip
      - unzip terraform.zip
      - move terraform /usr/local/bin/
  build:
    commands:
      - echo Initializing Terraform...
      - terraform init
      - echo Validating Terraform configuration...
      - terraform validate
      - echo Planning Terraform deployment...
      - terraform plan -out=tfplan
      - echo Applying Terraform...
      - terraform apply -auto-approve
artifacts:
  files:
    - '**/*'
